"""
query.py

Orchestrates the full RAG pipeline:
    load saved index → embed query → retrieve top-k → generate response

Public API
----------
ask(question: str, k: int = 5) -> dict
    Returns {"answer": str, "sources": list[str]}

The index and chunk list are loaded once at module level on first call
(lazy singleton) so repeated queries within the same process don't
reload from disk or re-embed.

Usage
-----
    from query import ask
    result = ask("what do students say about dorm safety at night")
    print(result["answer"])
    for src in result["sources"]:
        print(src)

CLI
---
    python query.py --query "tips for managing stress in college"
    python query.py --eval          # runs all 5 Evaluation Plan questions
"""

import argparse
import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()  # pick up GROQ_API_KEY from .env

# ---------------------------------------------------------------------------
# Lazy-loaded pipeline state (initialised once on first ask() call)
# ---------------------------------------------------------------------------

_state: dict | None = None   # holds {index, metadata}


def _load_pipeline() -> dict:
    """Load index and metadata from disk. Called once.

    Text is stored inside metadata (by build_index), so no separate
    chunk list is needed — the pipeline is fully self-contained.
    """
    from embed_retrieve import load_index

    base_dir = Path(__file__).parent
    index_path = str(base_dir / "docs" / "index.faiss")
    meta_path  = str(base_dir / "docs" / "index_meta.json")

    if not Path(index_path).exists():
        raise FileNotFoundError(
            f"Index not found at {index_path}. "
            "Run `python embed_retrieve.py` first to build it."
        )

    index, metadata = load_index(index_path, meta_path)
    return {"index": index, "metadata": metadata}


def _get_pipeline() -> dict:
    global _state
    if _state is None:
        _state = _load_pipeline()
    return _state


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def ask(question: str, k: int = 5) -> dict:
    """Run the full RAG pipeline for a question.

    Args:
        question : Natural-language query from the user.
        k        : Number of chunks to retrieve (default 5).

    Returns:
        {
            "answer"  : str   — grounded response with inline citations,
            "sources" : list[str] — human-readable source labels, one per
                        retrieved chunk (programmatically assembled, not
                        generated by the LLM).
        }
    """
    from embed_retrieve import retrieve
    from generate import generate

    pipeline = _get_pipeline()

    # Retrieve — text is stored in metadata, no separate chunk list needed
    retrieved = retrieve(
        question,
        pipeline["index"],
        pipeline["metadata"],
        k=k,
    )

    # Programmatic source list — guaranteed regardless of what the LLM says
    sources: list[str] = []
    for i, chunk in enumerate(retrieved, 1):
        source_type    = chunk.get("source_type", "unknown")
        url            = chunk.get("url", "")
        published_date = chunk.get("published_date", "")
        chunk_id       = chunk.get("chunk_id", "")
        score          = chunk.get("score", 0.0)
        sources.append(
            f"[Source {i}] {source_type} — {url} "
            f"(chunk: {chunk_id}, score: {score:.4f}, published: {published_date})"
        )

    # Generate
    answer = generate(question, retrieved)

    return {"answer": answer, "sources": sources}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

# Evaluation Plan questions from planning.md
_EVAL_QUESTIONS = [
    "What do students at Penn say about the quality of dorm mattresses and what do they recommend bringing?",
    "What free late-night transportation option do UW Oshkosh students recommend for walking alone at night?",
    "What specific mental health accommodation did the student author of Alex's Declassified College Survival Guide obtain, and what was the outcome?",
    "What do University of Michigan students say about dining hall food quality according to Niche student reviews?",
    "What do UMass students advise about taking classes outside your major during the first year?",
]


def _print_result(question: str, result: dict) -> None:
    print(f"\nQ: {question}")
    print("-" * 60)
    print(result["answer"])
    print("\nRetrieved from:")
    for src in result["sources"]:
        print(f"  {src}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Campus survival guide RAG — end-to-end query interface"
    )
    parser.add_argument("--query", type=str, default=None, help="Single question to ask.")
    parser.add_argument("--eval",  action="store_true",    help="Run all 5 Evaluation Plan questions.")
    args = parser.parse_args()

    if args.query:
        result = ask(args.query)
        _print_result(args.query, result)

    else:
        # Default: run eval suite
        print("=" * 70)
        print("EVALUATION RUN — planning.md §Evaluation Plan (5 questions)")
        print("=" * 70)
        for i, question in enumerate(_EVAL_QUESTIONS, 1):
            print(f"\n{'─' * 70}")
            print(f"Q{i}: {question}")
            print("─" * 70)
            try:
                result = ask(question)
                _print_result(question, result)
            except Exception as exc:
                print(f"[ERROR] {exc}")
        print(f"\n{'=' * 70}")
        print("Done. Score each answer against planning.md §Evaluation Plan.")
